http:
  port: "8081"
  
sfdc:
  username: "daniel.ramezani85@gmail.com"
  password: "M136430@r"
  token: "mgFhOXdu20QoRQmOZRZsSFxO"
  
file:
  accountsDir: "D:/AnypointStudio/NJCLAbs/MUFundamentals4.3_studentFiles_12may2020/MUFundamentals4.3_studentFiles_12may2020/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"